export const home = '/'
export const login = '/auth/login'
export const register = '/auth/register'
export const dashboard = '/dashboard'
export const products = '/products'
export const addproduct = '/form'
export const productDetail = '/form/:id'
